name: is_odd_or_even
description: Minimalist and elegant API that returns true if the given number is odd or even.
version: 1.0.0
homepage: https://github.com/arnemolland/is_odd_or_even

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  is_odd: ^1.0.0
  is_even: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
